# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x12\n\x10GetLeaderRequest\"-\n\x0eGetLeaderReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\" \n\x0eSuspendRequest\x12\x0e\n\x06period\x18\x01 \x01(\x05\"\x0e\n\x0cSuspendReply2d\n\x06server\x12/\n\tgetLeader\x12\x11.GetLeaderRequest\x1a\x0f.GetLeaderReply\x12)\n\x07suspend\x12\x0f.SuspendRequest\x1a\r.SuspendReplyb\x06proto3')



_GETLEADERREQUEST = DESCRIPTOR.message_types_by_name['GetLeaderRequest']
_GETLEADERREPLY = DESCRIPTOR.message_types_by_name['GetLeaderReply']
_SUSPENDREQUEST = DESCRIPTOR.message_types_by_name['SuspendRequest']
_SUSPENDREPLY = DESCRIPTOR.message_types_by_name['SuspendReply']
GetLeaderRequest = _reflection.GeneratedProtocolMessageType('GetLeaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLEADERREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:GetLeaderRequest)
  })
_sym_db.RegisterMessage(GetLeaderRequest)

GetLeaderReply = _reflection.GeneratedProtocolMessageType('GetLeaderReply', (_message.Message,), {
  'DESCRIPTOR' : _GETLEADERREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:GetLeaderReply)
  })
_sym_db.RegisterMessage(GetLeaderReply)

SuspendRequest = _reflection.GeneratedProtocolMessageType('SuspendRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDREQUEST,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SuspendRequest)
  })
_sym_db.RegisterMessage(SuspendRequest)

SuspendReply = _reflection.GeneratedProtocolMessageType('SuspendReply', (_message.Message,), {
  'DESCRIPTOR' : _SUSPENDREPLY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SuspendReply)
  })
_sym_db.RegisterMessage(SuspendReply)

_SERVER = DESCRIPTOR.services_by_name['server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETLEADERREQUEST._serialized_start=14
  _GETLEADERREQUEST._serialized_end=32
  _GETLEADERREPLY._serialized_start=34
  _GETLEADERREPLY._serialized_end=79
  _SUSPENDREQUEST._serialized_start=81
  _SUSPENDREQUEST._serialized_end=113
  _SUSPENDREPLY._serialized_start=115
  _SUSPENDREPLY._serialized_end=129
  _SERVER._serialized_start=131
  _SERVER._serialized_end=231
# @@protoc_insertion_point(module_scope)
