# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import raft_pb2 as raft__pb2


class serverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLeader = channel.unary_unary(
                '/server/getLeader',
                request_serializer=raft__pb2.GetLeaderRequest.SerializeToString,
                response_deserializer=raft__pb2.GetLeaderReply.FromString,
                )
        self.suspend = channel.unary_unary(
                '/server/suspend',
                request_serializer=raft__pb2.SuspendRequest.SerializeToString,
                response_deserializer=raft__pb2.SuspendReply.FromString,
                )


class serverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def suspend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_serverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.getLeader,
                    request_deserializer=raft__pb2.GetLeaderRequest.FromString,
                    response_serializer=raft__pb2.GetLeaderReply.SerializeToString,
            ),
            'suspend': grpc.unary_unary_rpc_method_handler(
                    servicer.suspend,
                    request_deserializer=raft__pb2.SuspendRequest.FromString,
                    response_serializer=raft__pb2.SuspendReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server/getLeader',
            raft__pb2.GetLeaderRequest.SerializeToString,
            raft__pb2.GetLeaderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def suspend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server/suspend',
            raft__pb2.SuspendRequest.SerializeToString,
            raft__pb2.SuspendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
