# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\"\x1a\n\nPutRequest\x12\x0c\n\x04item\x18\x01 \x01(\t\"\x1a\n\x08PutReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\r\n\x0bPeekRequest\")\n\tPeekReply\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\x0c\n\nPopRequest\"(\n\x08PopReply\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\"\r\n\x0bSizeRequest\"\x19\n\tSizeReply\x12\x0c\n\x04size\x18\x01 \x01(\x05\x32\x95\x01\n\x05queue\x12#\n\x07PutItem\x12\x0b.PutRequest\x1a\t.PutReply\"\x00\x12\"\n\x04Peek\x12\x0c.PeekRequest\x1a\n.PeekReply\"\x00\x12\x1f\n\x03Pop\x12\x0b.PopRequest\x1a\t.PopReply\"\x00\x12\"\n\x04Size\x12\x0c.SizeRequest\x1a\n.SizeReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUTREQUEST._serialized_start=15
  _PUTREQUEST._serialized_end=41
  _PUTREPLY._serialized_start=43
  _PUTREPLY._serialized_end=69
  _PEEKREQUEST._serialized_start=71
  _PEEKREQUEST._serialized_end=84
  _PEEKREPLY._serialized_start=86
  _PEEKREPLY._serialized_end=127
  _POPREQUEST._serialized_start=129
  _POPREQUEST._serialized_end=141
  _POPREPLY._serialized_start=143
  _POPREPLY._serialized_end=183
  _SIZEREQUEST._serialized_start=185
  _SIZEREQUEST._serialized_end=198
  _SIZEREPLY._serialized_start=200
  _SIZEREPLY._serialized_end=225
  _QUEUE._serialized_start=228
  _QUEUE._serialized_end=377
# @@protoc_insertion_point(module_scope)
