# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\"\x1e\n\x0eReverseRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\x0cReverseReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0cSplitRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tdelimiter\x18\x02 \x01(\t\"+\n\nSplitReply\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05parts\x18\x02 \x03(\t\" \n\x0eisPrimeRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"%\n\x0cisPrimeReply\x12\x15\n\rnumber_primer\x18\x01 \x01(\t2:\n\x07reverse\x12/\n\rReverseString\x12\x0f.ReverseRequest\x1a\r.ReverseReply22\n\x05split\x12)\n\x0bsplitString\x12\r.SplitRequest\x1a\x0b.SplitReply29\n\x07isPrime\x12.\n\x08is_prime\x12\x0f.isPrimeRequest\x1a\r.isPrimeReply(\x01\x30\x01\x62\x06proto3')

_REVERSEREQUEST = DESCRIPTOR.message_types_by_name['ReverseRequest']
_REVERSEREPLY = DESCRIPTOR.message_types_by_name['ReverseReply']
_SPLITREQUEST = DESCRIPTOR.message_types_by_name['SplitRequest']
_SPLITREPLY = DESCRIPTOR.message_types_by_name['SplitReply']
_ISPRIMEREQUEST = DESCRIPTOR.message_types_by_name['isPrimeRequest']
_ISPRIMEREPLY = DESCRIPTOR.message_types_by_name['isPrimeReply']
ReverseRequest = _reflection.GeneratedProtocolMessageType('ReverseRequest', (_message.Message,), {
    'DESCRIPTOR': _REVERSEREQUEST,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:ReverseRequest)
})
_sym_db.RegisterMessage(ReverseRequest)

ReverseReply = _reflection.GeneratedProtocolMessageType('ReverseReply', (_message.Message,), {
    'DESCRIPTOR': _REVERSEREPLY,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:ReverseReply)
})
_sym_db.RegisterMessage(ReverseReply)

SplitRequest = _reflection.GeneratedProtocolMessageType('SplitRequest', (_message.Message,), {
    'DESCRIPTOR': _SPLITREQUEST,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:SplitRequest)
})
_sym_db.RegisterMessage(SplitRequest)

SplitReply = _reflection.GeneratedProtocolMessageType('SplitReply', (_message.Message,), {
    'DESCRIPTOR': _SPLITREPLY,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:SplitReply)
})
_sym_db.RegisterMessage(SplitReply)

isPrimeRequest = _reflection.GeneratedProtocolMessageType('isPrimeRequest', (_message.Message,), {
    'DESCRIPTOR': _ISPRIMEREQUEST,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:isPrimeRequest)
})
_sym_db.RegisterMessage(isPrimeRequest)

isPrimeReply = _reflection.GeneratedProtocolMessageType('isPrimeReply', (_message.Message,), {
    'DESCRIPTOR': _ISPRIMEREPLY,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:isPrimeReply)
})
_sym_db.RegisterMessage(isPrimeReply)

_REVERSE = DESCRIPTOR.services_by_name['reverse']
_SPLIT = DESCRIPTOR.services_by_name['split']
_ISPRIME = DESCRIPTOR.services_by_name['isPrime']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _REVERSEREQUEST._serialized_start = 17
    _REVERSEREQUEST._serialized_end = 47
    _REVERSEREPLY._serialized_start = 49
    _REVERSEREPLY._serialized_end = 80
    _SPLITREQUEST._serialized_start = 82
    _SPLITREQUEST._serialized_end = 129
    _SPLITREPLY._serialized_start = 131
    _SPLITREPLY._serialized_end = 174
    _ISPRIMEREQUEST._serialized_start = 176
    _ISPRIMEREQUEST._serialized_end = 208
    _ISPRIMEREPLY._serialized_start = 210
    _ISPRIMEREPLY._serialized_end = 247
    _REVERSE._serialized_start = 249
    _REVERSE._serialized_end = 307
    _SPLIT._serialized_start = 309
    _SPLIT._serialized_end = 359
    _ISPRIME._serialized_start = 361
    _ISPRIME._serialized_end = 418
# @@protoc_insertion_point(module_scope)
